workflow:
  name: ProductDocumentation
  nodes:
    - id: GetProductInfoStep
      description: Gather information about the product
      implementation: Steps.GetProductInfoStep
      on_complete:
        - on_condition:
            type: default
            emits:
              - event_type: GetProductInfo.OnResult
    - id: GenerateDocumentationStep
      description: Generate documentation for the product with LLM
      implementation: Steps.GenerateDocumentationStep
      on_complete:
        - on_condition:
            type: default
            emits:
              - event_type: DocumentationGenerated
              - event_type: GenerateDocumentation.OnResult
    - id: PublishDocumentationStep
      description: Publish the documentation
      implementation: Steps.PublishDocumentationStep
      on_complete:
        - on_condition:
            type: default
            emits:
              - event_type: ProcessCompleted
  orchestration:
    - listen_for:
        event: InputMessageReceived
      then:
        - node: GetProductInfoStep
    - listen_for:
        event: GetProductInfo.OnResult
        from: GetProductInfoStep
      then:
        - node: GenerateDocumentationStep
    - listen_for:
        event: DocumentationGenerated
        from: GenerateDocumentationStep
      then:
        - node: PublishDocumentationStep
